// Icon names curated from lucide-react usage across the app.
/** @type {const} */
export const lucideIconNames = [
  'align-left',
  'arrow-left-right',
  'backpack',
  'badge-check',
  'bus',
  'briefcase',
  'binoculars',
  'building2',
  'calendar',
  'circle-check',
  'CircleQuestionMark',
  'check',
  'chevron-down',
  'chevron-left',
  'chevron-right',
  'dollar-sign',
  'file-text',
  'flame',
  'hand-coins',
  'hotel',
  'hourglass',
  'info',
  'kanban',
  'land-plot',
  'laptop',
  'list',
  'link-2',
  'map',
  'map-pin',
  'menu',
  'megaphone',
  'mountain',
  'palette',
  'pencil',
  'plane',
  'plus',
  'share-2',
  'shopping-cart',
  'sparkles',
  'ticket',
  'trash-2',
  'user',
  'user-star',
  'users',
  'utensils',
  'x',
];

export const lucideIconList = new Set(lucideIconNames);
