// Icon names curated from lucide-react usage across the app.
/** @type {const} */
export const lucideIconNames = [
  'align-left',
  'arrow-left-right',
  'bus',
  'calendar',
  'circle-check',
  'check',
  'chevron-down',
  'chevron-left',
  'chevron-right',
  'dollar-sign',
  'file-text',
  'hotel',
  'hourglass',
  'laptop',
  'list',
  'map',
  'map-pin',
  'menu',
  'mountain',
  'palette',
  'pencil',
  'plus',
  'shopping-cart',
  'user',
  'users',
  'userStar',
  'ticket',
  'trash-2',
  'utensils',
  'x',
];

export const lucideIconList = new Set(lucideIconNames);
