import type { LucideIcon } from 'lucide-react';
import {
  AlignLeft,
  ArrowLeftRight,
  Bus,
  Calendar,
  Check,
  ChevronDown,
  ChevronDownIcon,
  ChevronLeft,
  ChevronLeftIcon,
  ChevronRight,
  ChevronRightIcon,
  DollarSign,
  FileText,
  Hotel,
  Hourglass,
  List,
  Map,
  MapPin,
  Menu,
  Palette,
  Pencil,
  Plus,
  ShoppingCart,
  Ticket,
  Trash2,
  Utensils,
  X,
} from 'lucide-react';

import type { LucideIconName } from './icon-names';

export {
  AlignLeft,
  ArrowLeftRight,
  Bus,
  Calendar,
  Check,
  ChevronDown,
  ChevronDownIcon,
  ChevronLeft,
  ChevronLeftIcon,
  ChevronRight,
  ChevronRightIcon,
  DollarSign,
  FileText,
  Hotel,
  Hourglass,
  List,
  Map,
  MapPin,
  Menu,
  Palette,
  Pencil,
  Plus,
  ShoppingCart,
  Ticket,
  Trash2,
  Utensils,
  X,
  Calendar as CalendarIcon,
};

export const lucideIcons = {
  'align-left': AlignLeft,
  'arrow-left-right': ArrowLeftRight,
  bus: Bus,
  calendar: Calendar,
  check: Check,
  'chevron-down': ChevronDown,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'dollar-sign': DollarSign,
  'file-text': FileText,
  hotel: Hotel,
  hourglass: Hourglass,
  list: List,
  map: Map,
  'map-pin': MapPin,
  menu: Menu,
  palette: Palette,
  pencil: Pencil,
  plus: Plus,
  'shopping-cart': ShoppingCart,
  ticket: Ticket,
  'trash-2': Trash2,
  utensils: Utensils,
  x: X,
} as const satisfies Record<LucideIconName, LucideIcon>;
