name: CI

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: npm
          cache-dependency-path: package-lock.json
      - run: npm ci
      - run: npm run format:check
      - run: npm run lint
      - run: npm run typecheck
      - name: Build (Next.js)
        run: npm run build
      - name: Test (coverage)
        run: npm run test:coverage
      - run: npm run lint:commit
      - name: Vercel Pull (preview env)
        if: ${{ env.VERCEL_TOKEN != '' }}
        run: npm run vercel:pull
      - name: Vercel Build
        if: ${{ env.VERCEL_TOKEN != '' }}
        run: npm run vercel:build
      - name: Upload Vercel Build Artifact
        if: ${{ env.VERCEL_TOKEN != '' }}
        uses: actions/upload-artifact@v4
        with:
          name: vercel-output-${{ github.sha }}
          path: .vercel/output/**
          if-no-files-found: warn
